source "https://rubygems.org"

ruby "3.0.2"

gem "bootsnap", require: false

gem 'devise'

gem 'devise-jwt'

gem 'jsonapi-serializer'


gem "rails", "~> 7.1.4", ">= 7.1.4.2"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

# gem "jbuilder"
# gem "redis", ">= 4.0.1"
# gem "kredis"
# gem "bcrypt", "~> 3.1.7"


# gem "image_processing", "~> 1.2"
gem "rack-cors"


group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :development do
  # gem "spring"
end
